server:
  port: 9091
spring:
  application:
    name: spring-amazon
  datasource:
    name: test
    #url: jdbc:mysql://127.0.0.1:3306/vhr?useUnicode=true&characterEncoding=UTF-8
    #Mysql8.0以上版本,由于MySql8.0废弃了convertToNull该写法，改为 CONVERT_TO_NULL
    url: jdbc:mysql://db4free.net:3306/galen_db?characterEncoding=utf8&serverTimezone=UTC&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: user_galen
    password:  Galen*10*
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    #driver-class-name: com.mysql.jdbc.Driver
    #Mysql8.0以上版本
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  # 格式化时间
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # 邮件
  mail:
    port: 465
    host: smtp.163.com
    username: 17722515203@163.com
    password: Czx19910510
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          auth: true
          starttls:
            enable: true
            required: true
mybatis-plus:
  mapper-locations: classpath:mybatis/mappers/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.galen.amazon.entity
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: INPUT
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: NOT_NULL
      #驼峰下划线转换
      column-underline: true
      logic-delete-value: -1
      logic-not-delete-value: 0
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: false #禁用合理化,pageNum>pages会返回空数据
  supportMethodsArguments: true
  params: count=countSql
#日志输出配置
logging:
  level:
    root: INFO
    org.springframework: INFO
    com.galen.amazon.mapper: DEBUG
